import { StyleSheet, StatusBar } from 'react-native';
import { lightColors, darkColors } from '../theme/colors';

export const createHomeStyles = (colors: typeof lightColors | typeof darkColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      height: '100%'
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 24,
      paddingTop: 12,
      marginBottom: 8,
    },
    locationContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    locationLabel: {
      fontSize: 13,
      color: colors.description,
      fontWeight: '500',
    },
    locationText: {
      fontSize: 16,
      fontWeight: 'bold',
      color: colors.title,
    },
    notificationButton: {
      padding: 10,
      backgroundColor: colors.card,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 24,
      marginBottom: 24,
      gap: 12,
    },
    searchInputContainer: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.card,
      borderRadius: 16,
      paddingHorizontal: 16,
      height: 48,
      gap: 8,
    },
    searchInput: {
      flex: 1,
      fontSize: 16,
      color: colors.text,
    },
    filterButton: {
      backgroundColor: colors.button,
      borderRadius: 16,
      padding: 12,
      width: 48,
      height: 48,
      justifyContent: 'center',
      alignItems: 'center',
    },
    section: {
      marginBottom: 24,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 24,
      marginBottom: 14,
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: colors.title,
    },
    seeAllText: {
      fontSize: 15,
      color: colors.button,
      fontWeight: 'bold',
    },
    categoriesList: {
      paddingHorizontal: 24,
      marginBottom: 8,
    },
    categoryButton: {
      alignItems: 'center',
      marginRight: 18,
    },
    categoryIconContainer: {
      backgroundColor: colors.card,
      borderRadius: 18,
      padding: 20,
      marginBottom: 8,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: colors.border,
    },
    categoryText: {
      fontSize: 15,
      color: colors.description,
      fontWeight: '600',
    },
    listingsList: {
      paddingHorizontal: 24,
    },
    listingCard: {
      width: 220,
      backgroundColor: colors.card,
      borderRadius: 24,
      marginRight: 18,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 4,
      overflow: 'hidden',
    },
    listingImage: {
      width: '100%',
      height: 120,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
    },
    listingInfo: {
      padding: 16,
      position: 'relative',
    },
    listingRatingContainer: {
      position: 'absolute',
      top: -18,
      right: 16,
      backgroundColor: colors.background,
      borderRadius: 12,
      paddingHorizontal: 8,
      paddingVertical: 2,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 3,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.10,
      shadowRadius: 4,
      elevation: 2,
    },
    listingRatingText: {
      color: colors.star,
      fontSize: 13,
      fontWeight: 'bold',
    },
    listingType: {
      fontSize: 13,
      color: colors.button,
      marginBottom: 4,
      fontWeight: 'bold',
    },
    listingPriceContainer: {
      flexDirection: 'row',
      alignItems: 'baseline',
      marginBottom: 4,
      gap: 4,
    },
    listingPrice: {
      fontSize: 18,
      fontWeight: 'bold',
      color: colors.button,
    },
    listingPeriod: {
      fontSize: 13,
      color: colors.description,
      marginLeft: 2,
    },
    listingTitle: {
      fontSize: 15,
      fontWeight: 'bold',
      color: colors.title,
      marginBottom: 4,
    },
    listingLocationContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
      gap: 4,
    },
    listingLocationText: {
      fontSize: 13,
      color: colors.description,
    },
    heartIconContainer: {
      position: 'absolute',
      bottom: 10,
      right: 10,
      backgroundColor: colors.background,
      borderRadius: 15,
      padding: 6,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.10,
      shadowRadius: 2,
      elevation: 1,
    },
  }); 